#!/bin/bash
echo "🚀 Render Deployment Guide for CV Tailoring App"
echo ""
echo "📋 Step 1: Push to GitHub"
echo "git add ."
echo "git commit -m 'Ready for Render deployment'"
echo "git push origin main"
echo ""
echo "📋 Step 2: Create Render Service"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect GitHub repository: ai-cv-tailoring-app"
echo "4. Configure:"
echo "   - Environment: Node"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm start"
echo "   - Node Version: 18"
echo ""
echo "📋 Step 3: Environment Variables"
echo "Add these in Render dashboard:"
echo "   NODE_ENV = production"
echo "   GEMINI_API_KEY_1 = [your-first-api-key]"
echo "   GEMINI_API_KEY_2 = [your-second-api-key]"
echo ""
echo "📋 Step 4: Deploy!"
echo "Click 'Create Web Service' - takes ~5-10 minutes"
echo ""
echo "🌐 Your app will be at: https://your-app-name.onrender.com"
echo ""
echo "✅ Features after deployment:"
echo "   🤖 AI-powered CV tailoring"
echo "   🌍 Global location intelligence"
echo "   📄 Professional PDF export"
echo "   📊 ATS scoring"
echo "   🔒 SSL security"
echo "   📈 Auto-scaling"
