// Location detection and formatting utilities
// Ported from cityCountryDatabase.js for serverless functions

const cityCountryMap: { [key: string]: string } = {
  // Major cities with their countries
  "new york": "United States",
  "los angeles": "United States",
  "chicago": "United States",
  "houston": "United States",
  "phoenix": "United States",
  "philadelphia": "United States",
  "san antonio": "United States",
  "san diego": "United States",
  "dallas": "United States",
  "san jose": "United States",
  "austin": "United States",
  "jacksonville": "United States",
  "fort worth": "United States",
  "columbus": "United States",
  "charlotte": "United States",
  "san francisco": "United States",
  "indianapolis": "United States",
  "seattle": "United States",
  "denver": "United States",
  "washington": "United States",
  "boston": "United States",
  "el paso": "United States",
  "nashville": "United States",
  "detroit": "United States",
  "oklahoma city": "United States",
  "portland": "United States",
  "las vegas": "United States",
  "memphis": "United States",
  "louisville": "United States",
  "baltimore": "United States",
  "milwaukee": "United States",
  "albuquerque": "United States",
  "tucson": "United States",
  "fresno": "United States",
  "mesa": "United States",
  "sacramento": "United States",
  "atlanta": "United States",
  "kansas city": "United States",
  "colorado springs": "United States",
  "omaha": "United States",
  "raleigh": "United States",
  "miami": "United States",
  "long beach": "United States",
  "virginia beach": "United States",
  "oakland": "United States",
  "minneapolis": "United States",
  "tulsa": "United States",
  "arlington": "United States",
  "tampa": "United States",
  "new orleans": "United States",
  "wichita": "United States",
  "cleveland": "United States",
  "bakersfield": "United States",
  "aurora": "United States",
  "anaheim": "United States",
  "honolulu": "United States",
  "santa ana": "United States",
  "riverside": "United States",
  "corpus christi": "United States",
  "lexington": "United States",
  "stockton": "United States",
  "henderson": "United States",
  "saint paul": "United States",
  "st. paul": "United States",
  "cincinnati": "United States",
  "pittsburgh": "United States",
  
  // Canada
  "toronto": "Canada",
  "montreal": "Canada",
  "vancouver": "Canada",
  "calgary": "Canada",
  "edmonton": "Canada",
  "ottawa": "Canada",
  "winnipeg": "Canada",
  "quebec city": "Canada",
  "hamilton": "Canada",
  "kitchener": "Canada",
  "london": "Canada", // Note: This could be UK too, context matters
  "victoria": "Canada",
  "halifax": "Canada",
  "saskatoon": "Canada",
  "regina": "Canada",
  "st. john's": "Canada",
  "fredericton": "Canada",
  "charlottetown": "Canada",
  "yellowknife": "Canada",
  "whitehorse": "Canada",
  "iqaluit": "Canada",
  
  // UK
  "london": "United Kingdom",
  "birmingham": "United Kingdom",
  "manchester": "United Kingdom",
  "glasgow": "United Kingdom",
  "liverpool": "United Kingdom",
  "leeds": "United Kingdom",
  "sheffield": "United Kingdom",
  "edinburgh": "United Kingdom",
  "bristol": "United Kingdom",
  "cardiff": "United Kingdom",
  "belfast": "United Kingdom",
  "newcastle": "United Kingdom",
  "nottingham": "United Kingdom",
  "plymouth": "United Kingdom",
  "stoke-on-trent": "United Kingdom",
  "wolverhampton": "United Kingdom",
  "derby": "United Kingdom",
  "swansea": "United Kingdom",
  "southampton": "United Kingdom",
  "salford": "United Kingdom",
  "aberdeen": "United Kingdom",
  "westminster": "United Kingdom",
  "portsmouth": "United Kingdom",
  "york": "United Kingdom",
  "peterborough": "United Kingdom",
  "dundee": "United Kingdom",
  "lancaster": "United Kingdom",
  "oxford": "United Kingdom",
  "cambridge": "United Kingdom",
  "bath": "United Kingdom",
  "canterbury": "United Kingdom",
  "chester": "United Kingdom",
  "durham": "United Kingdom",
  "exeter": "United Kingdom",
  "gloucester": "United Kingdom",
  "hereford": "United Kingdom",
  "lichfield": "United Kingdom",
  "lincoln": "United Kingdom",
  "norwich": "United Kingdom",
  "ripon": "United Kingdom",
  "salisbury": "United Kingdom",
  "truro": "United Kingdom",
  "wakefield": "United Kingdom",
  "wells": "United Kingdom",
  "winchester": "United Kingdom",
  "worcester": "United Kingdom",
  
  // Australia
  "sydney": "Australia",
  "melbourne": "Australia",
  "brisbane": "Australia",
  "perth": "Australia",
  "adelaide": "Australia",
  "gold coast": "Australia",
  "newcastle": "Australia",
  "canberra": "Australia",
  "sunshine coast": "Australia",
  "wollongong": "Australia",
  "hobart": "Australia",
  "geelong": "Australia",
  "townsville": "Australia",
  "cairns": "Australia",
  "darwin": "Australia",
  "toowoomba": "Australia",
  "ballarat": "Australia",
  "bendigo": "Australia",
  "albury": "Australia",
  "launceston": "Australia",
  "mackay": "Australia",
  "rockhampton": "Australia",
  "bunbury": "Australia",
  "bundaberg": "Australia",
  "coffs harbour": "Australia",
  "wagga wagga": "Australia",
  "hervey bay": "Australia",
  "mildura": "Australia",
  "shepparton": "Australia",
  "port macquarie": "Australia",
  
  // India
  "mumbai": "India",
  "delhi": "India",
  "bangalore": "India",
  "hyderabad": "India",
  "ahmedabad": "India",
  "chennai": "India",
  "kolkata": "India",
  "surat": "India",
  "pune": "India",
  "jaipur": "India",
  "lucknow": "India",
  "kanpur": "India",
  "nagpur": "India",
  "indore": "India",
  "thane": "India",
  "bhopal": "India",
  "visakhapatnam": "India",
  "pimpri-chinchwad": "India",
  "patna": "India",
  "vadodara": "India",
  "ghaziabad": "India",
  "ludhiana": "India",
  "agra": "India",
  "nashik": "India",
  "faridabad": "India",
  "meerut": "India",
  "rajkot": "India",
  "kalyan-dombivli": "India",
  "vasai-virar": "India",
  "varanasi": "India",
  "srinagar": "India",
  "aurangabad": "India",
  "dhanbad": "India",
  "amritsar": "India",
  "navi mumbai": "India",
  "allahabad": "India",
  "ranchi": "India",
  "howrah": "India",
  "coimbatore": "India",
  "jabalpur": "India",
  "gwalior": "India",
  "vijayawada": "India",
  "jodhpur": "India",
  "madurai": "India",
  "raipur": "India",
  "kota": "India",
  "guwahati": "India",
  "chandigarh": "India",
  "solapur": "India",
  "hubli-dharwad": "India",
  "tiruchirappalli": "India",
  "bareilly": "India",
  "mysore": "India",
  "tiruppur": "India",
  "gurgaon": "India",
  "aligarh": "India",
  "jalandhar": "India",
  "bhubaneswar": "India",
  "salem": "India",
  "warangal": "India",
  "guntur": "India",
  "bhiwandi": "India",
  "saharanpur": "India",
  "gorakhpur": "India",
  "bikaner": "India",
  "amravati": "India",
  "noida": "India",
  "jamshedpur": "India",
  "bhilai": "India",
  "cuttack": "India",
  "firozabad": "India",
  "kochi": "India",
  "nellore": "India",
  "bhavnagar": "India",
  "dehradun": "India",
  "durgapur": "India",
  "asansol": "India",
  "rourkela": "India",
  "nanded": "India",
  "kolhapur": "India",
  "ajmer": "India",
  "akola": "India",
  "gulbarga": "India",
  "jamnagar": "India",
  "ujjain": "India",
  "loni": "India",
  "siliguri": "India",
  "jhansi": "India",
  "ulhasnagar": "India",
  "jammu": "India",
  "sangli-miraj & kupwad": "India",
  "mangalore": "India",
  "erode": "India",
  "belgaum": "India",
  "ambattur": "India",
  "tirunelveli": "India",
  "malegaon": "India",
  "gaya": "India",
  "jalgaon": "India",
  "udaipur": "India",
  "maheshtala": "India",
  
  // Other major global cities
  "tokyo": "Japan",
  "osaka": "Japan",
  "kyoto": "Japan",
  "yokohama": "Japan",
  "nagoya": "Japan",
  "sapporo": "Japan",
  "fukuoka": "Japan",
  "kobe": "Japan",
  "kawasaki": "Japan",
  "saitama": "Japan",
  
  "beijing": "China",
  "shanghai": "China",
  "guangzhou": "China",
  "shenzhen": "China",
  "tianjin": "China",
  "wuhan": "China",
  "dongguan": "China",
  "chengdu": "China",
  "nanjing": "China",
  "foshan": "China",
  "shenyang": "China",
  "qingdao": "China",
  "xi'an": "China",
  "suzhou": "China",
  "zhengzhou": "China",
  "dalian": "China",
  "jinan": "China",
  "hangzhou": "China",
  "harbin": "China",
  "kunming": "China",
  
  "seoul": "South Korea",
  "busan": "South Korea",
  "incheon": "South Korea",
  "daegu": "South Korea",
  "daejeon": "South Korea",
  "gwangju": "South Korea",
  "ulsan": "South Korea",
  "suwon": "South Korea",
  
  "singapore": "Singapore",
  
  "bangkok": "Thailand",
  "chiang mai": "Thailand",
  "phuket": "Thailand",
  "pattaya": "Thailand",
  
  "kuala lumpur": "Malaysia",
  "george town": "Malaysia",
  "ipoh": "Malaysia",
  "johor bahru": "Malaysia",
  
  "jakarta": "Indonesia",
  "surabaya": "Indonesia",
  "bandung": "Indonesia",
  "bekasi": "Indonesia",
  "medan": "Indonesia",
  "tangerang": "Indonesia",
  "depok": "Indonesia",
  "semarang": "Indonesia",
  "palembang": "Indonesia",
  "makassar": "Indonesia",
  
  "manila": "Philippines",
  "quezon city": "Philippines",
  "davao city": "Philippines",
  "cebu city": "Philippines",
  "zamboanga city": "Philippines",
  
  "ho chi minh city": "Vietnam",
  "hanoi": "Vietnam",
  "da nang": "Vietnam",
  "can tho": "Vietnam",
  
  "dhaka": "Bangladesh",
  "chittagong": "Bangladesh",
  "khulna": "Bangladesh",
  "rajshahi": "Bangladesh",
  
  "karachi": "Pakistan",
  "lahore": "Pakistan",
  "faisalabad": "Pakistan",
  "rawalpindi": "Pakistan",
  "multan": "Pakistan",
  "hyderabad": "Pakistan",
  "gujranwala": "Pakistan",
  "peshawar": "Pakistan",
  "quetta": "Pakistan",
  "islamabad": "Pakistan",
  
  "tehran": "Iran",
  "mashhad": "Iran",
  "isfahan": "Iran",
  "karaj": "Iran",
  "tabriz": "Iran",
  "shiraz": "Iran",
  "qom": "Iran",
  "ahvaz": "Iran",
  
  "istanbul": "Turkey",
  "ankara": "Turkey",
  "izmir": "Turkey",
  "bursa": "Turkey",
  "adana": "Turkey",
  "gaziantep": "Turkey",
  "konya": "Turkey",
  
  "moscow": "Russia",
  "saint petersburg": "Russia",
  "novosibirsk": "Russia",
  "yekaterinburg": "Russia",
  "nizhny novgorod": "Russia",
  "kazan": "Russia",
  "chelyabinsk": "Russia",
  "omsk": "Russia",
  "samara": "Russia",
  "rostov-on-don": "Russia",
  
  "berlin": "Germany",
  "hamburg": "Germany",
  "munich": "Germany",
  "cologne": "Germany",
  "frankfurt": "Germany",
  "stuttgart": "Germany",
  "düsseldorf": "Germany",
  "dortmund": "Germany",
  "essen": "Germany",
  "leipzig": "Germany",
  "bremen": "Germany",
  "dresden": "Germany",
  "hanover": "Germany",
  "nuremberg": "Germany",
  
  "paris": "France",
  "marseille": "France",
  "lyon": "France",
  "toulouse": "France",
  "nice": "France",
  "nantes": "France",
  "strasbourg": "France",
  "montpellier": "France",
  "bordeaux": "France",
  "lille": "France",
  "rennes": "France",
  "reims": "France",
  "le havre": "France",
  "saint-étienne": "France",
  "toulon": "France",
  "grenoble": "France",
  "dijon": "France",
  "angers": "France",
  "nîmes": "France",
  "villeurbanne": "France",
  
  "madrid": "Spain",
  "barcelona": "Spain",
  "valencia": "Spain",
  "seville": "Spain",
  "zaragoza": "Spain",
  "málaga": "Spain",
  "murcia": "Spain",
  "palma": "Spain",
  "las palmas": "Spain",
  "bilbao": "Spain",
  "alicante": "Spain",
  "córdoba": "Spain",
  "valladolid": "Spain",
  "vigo": "Spain",
  "gijón": "Spain",
  "hospitalet de llobregat": "Spain",
  "vitoria-gasteiz": "Spain",
  "a coruña": "Spain",
  "elche": "Spain",
  "oviedo": "Spain",
  
  "rome": "Italy",
  "milan": "Italy",
  "naples": "Italy",
  "turin": "Italy",
  "palermo": "Italy",
  "genoa": "Italy",
  "bologna": "Italy",
  "florence": "Italy",
  "bari": "Italy",
  "catania": "Italy",
  "venice": "Italy",
  "verona": "Italy",
  "messina": "Italy",
  "padua": "Italy",
  "trieste": "Italy",
  "taranto": "Italy",
  "brescia": "Italy",
  "prato": "Italy",
  "reggio calabria": "Italy",
  "modena": "Italy",
  
  "amsterdam": "Netherlands",
  "rotterdam": "Netherlands",
  "the hague": "Netherlands",
  "utrecht": "Netherlands",
  "eindhoven": "Netherlands",
  "tilburg": "Netherlands",
  "groningen": "Netherlands",
  "almere": "Netherlands",
  "breda": "Netherlands",
  "nijmegen": "Netherlands",
  
  "brussels": "Belgium",
  "antwerp": "Belgium",
  "ghent": "Belgium",
  "charleroi": "Belgium",
  "liège": "Belgium",
  "bruges": "Belgium",
  "namur": "Belgium",
  "leuven": "Belgium",
  
  "zurich": "Switzerland",
  "geneva": "Switzerland",
  "basel": "Switzerland",
  "lausanne": "Switzerland",
  "bern": "Switzerland",
  "winterthur": "Switzerland",
  "lucerne": "Switzerland",
  "st. gallen": "Switzerland",
  
  "vienna": "Austria",
  "graz": "Austria",
  "linz": "Austria",
  "salzburg": "Austria",
  "innsbruck": "Austria",
  
  "stockholm": "Sweden",
  "gothenburg": "Sweden",
  "malmö": "Sweden",
  "uppsala": "Sweden",
  "västerås": "Sweden",
  "örebro": "Sweden",
  "linköping": "Sweden",
  "helsingborg": "Sweden",
  "jönköping": "Sweden",
  "norrköping": "Sweden",
  
  "oslo": "Norway",
  "bergen": "Norway",
  "trondheim": "Norway",
  "stavanger": "Norway",
  "drammen": "Norway",
  "fredrikstad": "Norway",
  "kristiansand": "Norway",
  "sandnes": "Norway",
  "tromsø": "Norway",
  
  "copenhagen": "Denmark",
  "aarhus": "Denmark",
  "odense": "Denmark",
  "aalborg": "Denmark",
  "esbjerg": "Denmark",
  "randers": "Denmark",
  "kolding": "Denmark",
  "horsens": "Denmark",
  
  "helsinki": "Finland",
  "espoo": "Finland",
  "tampere": "Finland",
  "vantaa": "Finland",
  "oulu": "Finland",
  "turku": "Finland",
  "jyväskylä": "Finland",
  "lahti": "Finland",
  
  "reykjavik": "Iceland",
  
  "dublin": "Ireland",
  "cork": "Ireland",
  "limerick": "Ireland",
  "galway": "Ireland",
  "waterford": "Ireland",
  
  "lisbon": "Portugal",
  "porto": "Portugal",
  "amadora": "Portugal",
  "braga": "Portugal",
  "setúbal": "Portugal",
  "coimbra": "Portugal",
  "funchal": "Portugal",
  
  "athens": "Greece",
  "thessaloniki": "Greece",
  "patras": "Greece",
  "piraeus": "Greece",
  "larissa": "Greece",
  "heraklion": "Greece",
  
  "warsaw": "Poland",
  "kraków": "Poland",
  "łódź": "Poland",
  "wrocław": "Poland",
  "poznań": "Poland",
  "gdańsk": "Poland",
  "szczecin": "Poland",
  "bydgoszcz": "Poland",
  "lublin": "Poland",
  "katowice": "Poland",
  
  "prague": "Czech Republic",
  "brno": "Czech Republic",
  "ostrava": "Czech Republic",
  "plzen": "Czech Republic",
  
  "budapest": "Hungary",
  "debrecen": "Hungary",
  "szeged": "Hungary",
  "miskolc": "Hungary",
  "pécs": "Hungary",
  "győr": "Hungary",
  
  "bucharest": "Romania",
  "cluj-napoca": "Romania",
  "timișoara": "Romania",
  "iași": "Romania",
  "constanța": "Romania",
  "craiova": "Romania",
  "brașov": "Romania",
  "galați": "Romania",
  
  "sofia": "Bulgaria",
  "plovdiv": "Bulgaria",
  "varna": "Bulgaria",
  "burgas": "Bulgaria",
  "ruse": "Bulgaria",
  
  "zagreb": "Croatia",
  "split": "Croatia",
  "rijeka": "Croatia",
  "osijek": "Croatia",
  
  "belgrade": "Serbia",
  "novi sad": "Serbia",
  "niš": "Serbia",
  
  "ljubljana": "Slovenia",
  "maribor": "Slovenia",
  
  "skopje": "North Macedonia",
  
  "sarajevo": "Bosnia and Herzegovina",
  
  "pristina": "Kosovo",
  
  "podgorica": "Montenegro",
  
  "tirana": "Albania",
  
  "kiev": "Ukraine",
  "kharkiv": "Ukraine",
  "odessa": "Ukraine",
  "dnipro": "Ukraine",
  "donetsk": "Ukraine",
  "zaporizhzhia": "Ukraine",
  "lviv": "Ukraine",
  
  "minsk": "Belarus",
  
  "riga": "Latvia",
  
  "vilnius": "Lithuania",
  
  "tallinn": "Estonia",
  
  "cairo": "Egypt",
  "alexandria": "Egypt",
  "giza": "Egypt",
  "shubra el-kheima": "Egypt",
  "port said": "Egypt",
  "suez": "Egypt",
  "luxor": "Egypt",
  "aswan": "Egypt",
  
  "cape town": "South Africa",
  "johannesburg": "South Africa",
  "durban": "South Africa",
  "pretoria": "South Africa",
  "port elizabeth": "South Africa",
  "bloemfontein": "South Africa",
  "east london": "South Africa",
  "pietermaritzburg": "South Africa",
  
  "lagos": "Nigeria",
  "kano": "Nigeria",
  "ibadan": "Nigeria",
  "abuja": "Nigeria",
  "port harcourt": "Nigeria",
  "benin city": "Nigeria",
  "maiduguri": "Nigeria",
  "zaria": "Nigeria",
  "aba": "Nigeria",
  "jos": "Nigeria",
  
  "addis ababa": "Ethiopia",
  
  "nairobi": "Kenya",
  "mombasa": "Kenya",
  "nakuru": "Kenya",
  "eldoret": "Kenya",
  
  "dar es salaam": "Tanzania",
  "mwanza": "Tanzania",
  "arusha": "Tanzania",
  "dodoma": "Tanzania",
  
  "kampala": "Uganda",
  
  "kigali": "Rwanda",
  
  "casablanca": "Morocco",
  "rabat": "Morocco",
  "fez": "Morocco",
  "marrakech": "Morocco",
  "agadir": "Morocco",
  "tangier": "Morocco",
  "meknes": "Morocco",
  "oujda": "Morocco",
  
  "algiers": "Algeria",
  "oran": "Algeria",
  "constantine": "Algeria",
  "annaba": "Algeria",
  
  "tunis": "Tunisia",
  "sfax": "Tunisia",
  "sousse": "Tunisia",
  "kairouan": "Tunisia",
  
  "tripoli": "Libya",
  "benghazi": "Libya",
  
  "khartoum": "Sudan",
  
  "riyadh": "Saudi Arabia",
  "jeddah": "Saudi Arabia",
  "mecca": "Saudi Arabia",
  "medina": "Saudi Arabia",
  "dammam": "Saudi Arabia",
  "khobar": "Saudi Arabia",
  "tabuk": "Saudi Arabia",
  
  "dubai": "United Arab Emirates",
  "abu dhabi": "United Arab Emirates",
  "sharjah": "United Arab Emirates",
  "al ain": "United Arab Emirates",
  "ajman": "United Arab Emirates",
  "ras al-khaimah": "United Arab Emirates",
  "fujairah": "United Arab Emirates",
  
  "doha": "Qatar",
  
  "kuwait city": "Kuwait",
  
  "manama": "Bahrain",
  
  "muscat": "Oman",
  
  "sanaa": "Yemen",
  "aden": "Yemen",
  
  "amman": "Jordan",
  "zarqa": "Jordan",
  "irbid": "Jordan",
  
  "damascus": "Syria",
  "aleppo": "Syria",
  "homs": "Syria",
  "latakia": "Syria",
  
  "beirut": "Lebanon",
  "tripoli": "Lebanon",
  "sidon": "Lebanon",
  "tyre": "Lebanon",
  
  "jerusalem": "Israel",
  "tel aviv": "Israel",
  "haifa": "Israel",
  "rishon lezion": "Israel",
  "petah tikva": "Israel",
  "ashdod": "Israel",
  "netanya": "Israel",
  "beer sheva": "Israel",
  
  "mexico city": "Mexico",
  "ecatepec de morelos": "Mexico",
  "guadalajara": "Mexico",
  "puebla": "Mexico",
  "tijuana": "Mexico",
  "león": "Mexico",
  "juárez": "Mexico",
  "torreón": "Mexico",
  "querétaro": "Mexico",
  "san luis potosí": "Mexico",
  "mérida": "Mexico",
  "mexicali": "Mexico",
  "aguascalientes": "Mexico",
  "acapulco": "Mexico",
  "cuernavaca": "Mexico",
  "cancún": "Mexico",
  
  "guatemala city": "Guatemala",
  
  "belize city": "Belize",
  
  "san salvador": "El Salvador",
  
  "tegucigalpa": "Honduras",
  
  "managua": "Nicaragua",
  
  "san josé": "Costa Rica",
  
  "panama city": "Panama",
  
  "havana": "Cuba",
  "santiago de cuba": "Cuba",
  "camagüey": "Cuba",
  "holguín": "Cuba",
  "guantánamo": "Cuba",
  "santa clara": "Cuba",
  
  "kingston": "Jamaica",
  "spanish town": "Jamaica",
  "portmore": "Jamaica",
  
  "port-au-prince": "Haiti",
  
  "santo domingo": "Dominican Republic",
  "santiago de los caballeros": "Dominican Republic",
  
  "san juan": "Puerto Rico",
  "bayamón": "Puerto Rico",
  "carolina": "Puerto Rico",
  "ponce": "Puerto Rico",
  
  "caracas": "Venezuela",
  "maracaibo": "Venezuela",
  "valencia": "Venezuela",
  "barquisimeto": "Venezuela",
  "maracay": "Venezuela",
  "ciudad guayana": "Venezuela",
  
  "bogotá": "Colombia",
  "medellín": "Colombia",
  "cali": "Colombia",
  "barranquilla": "Colombia",
  "cartagena": "Colombia",
  "cúcuta": "Colombia",
  "bucaramanga": "Colombia",
  "pereira": "Colombia",
  "santa marta": "Colombia",
  "ibagué": "Colombia",
  
  "quito": "Ecuador",
  "guayaquil": "Ecuador",
  "cuenca": "Ecuador",
  "santo domingo": "Ecuador",
  "machala": "Ecuador",
  
  "lima": "Peru",
  "arequipa": "Peru",
  "trujillo": "Peru",
  "chiclayo": "Peru",
  "huancayo": "Peru",
  "piura": "Peru",
  "iquitos": "Peru",
  "cusco": "Peru",
  
  "la paz": "Bolivia",
  "santa cruz de la sierra": "Bolivia",
  "cochabamba": "Bolivia",
  "sucre": "Bolivia",
  "oruro": "Bolivia",
  "potosí": "Bolivia",
  
  "são paulo": "Brazil",
  "rio de janeiro": "Brazil",
  "salvador": "Brazil",
  "brasília": "Brazil",
  "fortaleza": "Brazil",
  "belo horizonte": "Brazil",
  "manaus": "Brazil",
  "curitiba": "Brazil",
  "recife": "Brazil",
  "porto alegre": "Brazil",
  "belém": "Brazil",
  "goiânia": "Brazil",
  "guarulhos": "Brazil",
  "campinas": "Brazil",
  "são luís": "Brazil",
  "são gonçalo": "Brazil",
  "maceió": "Brazil",
  "duque de caxias": "Brazil",
  "natal": "Brazil",
  "campo grande": "Brazil",
  
  "asunción": "Paraguay",
  "ciudad del este": "Paraguay",
  
  "montevideo": "Uruguay",
  
  "buenos aires": "Argentina",
  "córdoba": "Argentina",
  "rosario": "Argentina",
  "mendoza": "Argentina",
  "tucumán": "Argentina",
  "la plata": "Argentina",
  "mar del plata": "Argentina",
  "salta": "Argentina",
  "santa fe": "Argentina",
  "san juan": "Argentina",
  
  "santiago": "Chile",
  "valparaíso": "Chile",
  "concepción": "Chile",
  "la serena": "Chile",
  "antofagasta": "Chile",
  "temuco": "Chile",
  "rancagua": "Chile",
  "talca": "Chile",
  "arica": "Chile",
  "chillán": "Chile"
};

/**
 * Detects the country for a given city name
 * @param location - The location string to analyze
 * @returns The detected country name or null if not found
 */
export const detectCountryFromCity = (location: string): string | null => {
  if (!location || typeof location !== 'string') {
    return null;
  }
  
  const locationLower = location.toLowerCase().trim();
  
  // Direct city lookup
  if (cityCountryMap[locationLower]) {
    return cityCountryMap[locationLower];
  }
  
  // Try to extract city from location string (handle "City, State" format)
  const parts = locationLower.split(',');
  if (parts.length > 0) {
    const cityPart = parts[0].trim();
    if (cityCountryMap[cityPart]) {
      return cityCountryMap[cityPart];
    }
  }
  
  // Try to find partial matches
  for (const [city, country] of Object.entries(cityCountryMap)) {
    if (locationLower.includes(city)) {
      return country;
    }
  }
  
  return null;
};

/**
 * Formats location with country information
 * @param location - The original location string
 * @param country - The detected or provided country
 * @returns Formatted location string with country
 */
export const formatLocationWithCountry = (location: string, country?: string): string => {
  if (!location) {
    return '';
  }
  
  // If country is already mentioned in location, return as is
  if (country && location.toLowerCase().includes(country.toLowerCase())) {
    return location;
  }
  
  // If we have a country, append it
  if (country) {
    return `${location}, ${country}`;
  }
  
  return location;
};